### ISSUE TITLE
Can't get new fixes working like it was before

### ISSUE THREAD

**Issue by BoxJockey** [Nacurutu/Dark-Themes-SD-WebUI-Automatic1111#2]
Hi Nacurutu. I'm not able to get your new changes to display Txt2Img & Img2Img like they were before the recent Auto1111 broke everything. I've got the latest updates, reinstalled CSS App, shift-F5 but Nacurutu - Alani and Nacurutu - Neon both display like this ...

![Untitled (Small)](https://user-images.githubusercontent.com/22641919/214270511-b3d79b02-d445-47b8-9032-d98626dfe0c7.png)

Any ideas what I've done wrong or what I can try to implement your new fixes?

**Comment by Vilsepi** [comment]
Are you launching the server with argument `--theme=dark` or adding the `__theme=dark` query parameter in the URL (e.g. `http://localhost:8000/?__theme=dark`)?

Note that the WebUI had a bug related to this which was fixed yesterday (https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7048), so make sure you update to the latest WebUI again.

**Comment by Nacurutu** [comment]
@BoxJockey @Vilsepi Thanks to you both for using this css custom files.

Any recommendations are welcome.

**Comment by Gerschel** [comment]
> hi @BoxJockey
> 
> As @Vilsepi said, there was a bug with the webUI and the dark mode, however, it was already fixed.
> 
> Try updating the webUI and use the last files I have uploaded, should work properly.
> 
> I'm trying to keep the files up to date with the new changes/additions on the webUI.
> 
> Thanks for reporting the issue, I hope is working properly now.
> 
> Also, remember to add --theme=dark to the arguments. 👍🏻
> 
> I use the dark theme option to avoid any issues with the Vanilla theme, all of the code lines I add to the CSS file points to the dark theme (.dark).
> 
> Regarding the img2img tab layout, the last updates made me go back to the regular one, the way things are distributed now doesn't allow me to move/change the layout just using CSS. I get errors everywhere.

The hard part, it's a moving target. Sometimes it can change, you fix, then it changes back, maybe a curve ball thrown in for fun. Once you figure that out, it changes again.

**Comment by Nacurutu** [comment]
> The hard part, it's a moving target. Sometimes it can change, you fix, then it changes back, maybe a curve ball thrown in for fun. Once you figure that out, it changes again.

hahaha, that's correct. and as we depend on the webUI changes, nothing to do xD than try to fix new bugs. 

Also, waiting for the migration into the settings tab. No pressure, just a reminder, I know you are very busy with other projects. 

If you want. I can create a mockup of a layout for the setting tab :D 

I'm all ears.

**Comment by Nacurutu** [comment]
@BoxJockey @Vilsepi 

I pushed new files with minor fixes here and to the files on the @Gerschel extension. Give them a try and let me know to see if we close this issue as solved :)

**Comment by Nacurutu** [comment]
Regarding the img2img tab layout, the last webUI updates Auto1111 made, made me go back to the regular one, the way things are distributed now doesn't allow me to move/change the layout just using CSS. I get errors everywhere and everything is a mess, I had to remove all the code from the file. I'm still trying to figure out how to change it again because I love the way it looked, but trust me, it is difficult just modifying a CSS file because I can't add/remove things, I just can "move" or "change" some behaviors, but the structure is not very friendly at the moment, maybe in the future, if Auto updates the structure on how he places things on the UI, I will be able to move again things without breaking entirely the UI.

Sorry for that, still working on it, but I can't promise anything if Auto doesn't change the structure.

For example, he has a wrapper that includes the "save" Zip" "send to" buttons under the gallery mixed with the Sliders at the left, but not all of them. Also, the inpaint section is inside a flex-wrap, but trying to move this in paint section, makes all the sliders from the left impossible to use, I have tried a lot of different things without success. 

Also, I'm not an expert on CSS, I just use logic and my tiny knowledge of how CSS works. 

But trust me, I'm doing my best to bring back that because I love the way it looks and also avoid people scrolling down every time they want to use options on the actual layout.

Maybe I'm going to write to Auto and ask him if he can make some modifications on his end to allow me to make the changes. Who knows and maybe he accept.

**Comment by Nacurutu** [comment]
@BoxJockey regarding this:

> Also Nacurutu, I'm getting errors in the console if I select a style and hit Apply (Reload UI) but not if I hit Apply Style, then Apply Changes (Reload UI)

Yep, that's the way the extension works:

- select the theme file
- apply style
- reload UI

However, @Gerschel is working on a simple way, we r talking on how to make things simple and also, try to move the tab into the settings tab. 

good and simpler things coming in the near future

**Comment by Nacurutu** [comment]
@BoxJockey can I close the issue?

**Comment by BoxJockey** [comment]
Got it. I hope you get somewhere, because when it was working it was amazing not to have to scroll up and down to change stuff. (Especially Denoising Strength!!!) The default layout is quite awful. Thanks for doing this regardless if you find a way to make it work!

**Comment by Nacurutu** [comment]
> Got it. I hope you get somewhere, because when it was working it was amazing not to have to scroll up and down to change stuff. (Especially Denoising Strength!!!) The default layout is quite awful. Thanks for doing this regardless if you find a way to make it work!

I know is not comfortable to scroll up and down, that's why I tried to modify the layout, for the meantime, you can go to the settings tab, user interface, and reorder the panel.

change the "cfg" to the beginning of the list and the Denoising strength will be on top.

![image](https://user-images.githubusercontent.com/18109442/214389568-ec227b6f-beae-4774-8e1b-6df07c0db393.png)

![image](https://user-images.githubusercontent.com/18109442/214389648-e9d1e0e1-572d-4ac4-a31c-29f6ad876bfa.png)


At least is something until we figure out how to get back to the "new layout" structure.
